# Generated by Django 2.2.8 on 2020-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200706_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(max_length=34),
        ),
    ]
