# Generated by Django 2.2.8 on 2020-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('catname', models.CharField(max_length=34)),
                ('catid', models.IntegerField()),
            ],
        ),
    ]
